set(PROJ_DEFAULT_BUILD_TYPE "Debug")
if (NOT CMAKE_BUILD_TYPE AND NOT CMAKE_CONFIGURATION_TYPES)
    MESSAGE(WARNING "SetDefaultBuildType : Setting build type to ${PROJ_DEFAULT_BUILD_TYPE}, as none was specified.")
    set(CMAKE_BUILD_TYPE "${PROJ_DEFAULT_BUILD_TYPE}" CACHE STRING "Choose the type of build." FORCE)
    set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS "Debug" "Release" "MinSizeRel" "RelWithDebInfo")
endif()